#!/usr/bin/env python3
"""Build the standalone Layout Studio index.html from dependency-free sources."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "src"
TARGET = ROOT / "index.html"

REPLACEMENTS = {
    "/*__INLINE_STYLES__*/": SOURCE / "styles.css",
    "/*__INLINE_MODEL__*/": SOURCE / "model.js",
    "/*__INLINE_VIEWER__*/": SOURCE / "viewer.js",
    "/*__INLINE_APP__*/": SOURCE / "app.js",
}


def build_text() -> str:
    template = (SOURCE / "index.template.html").read_text(encoding="utf-8")
    result = template
    for marker, filename in REPLACEMENTS.items():
        if result.count(marker) != 1:
            raise RuntimeError(f"expected exactly one {marker!r} marker in the template")
        content = filename.read_text(encoding="utf-8").rstrip()
        result = result.replace(marker, content)
    banner = "<!-- Generated by webapp/build.py. Edit files under webapp/src instead. -->\n"
    if result.startswith("<!doctype html>"):
        result = result.replace("<!doctype html>\n", f"<!doctype html>\n{banner}", 1)
    else:
        result = banner + result
    return result.rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if index.html is not the current deterministic build",
    )
    args = parser.parse_args()

    built = build_text()
    if args.check:
        if not TARGET.exists():
            print(f"missing generated file: {TARGET}")
            return 1
        current = TARGET.read_text(encoding="utf-8")
        if current == built:
            print("index.html is up to date")
            return 0
        print("index.html is out of date; run: python3 build.py")
        diff = difflib.unified_diff(
            current.splitlines(),
            built.splitlines(),
            fromfile="index.html",
            tofile="rebuilt index.html",
            lineterm="",
            n=2,
        )
        for line in list(diff)[:80]:
            print(line)
        return 1

    TARGET.write_text(built, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(built):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
