#!/usr/bin/env python3
"""Refresh the checked-in webapp index.html from its source template."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "src" / "index.template.html"
TARGET = ROOT / "index.html"
BANNER = "<!-- Generated by webapp/build.py. Edit webapp/src/index.template.html instead. -->\n"


def build_text() -> str:
    template = SOURCE.read_text(encoding="utf-8")
    if not template.startswith("<!doctype html>\n"):
        raise RuntimeError("src/index.template.html must start with <!doctype html>")
    return template.replace("<!doctype html>\n", f"<!doctype html>\n{BANNER}", 1).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when index.html is stale")
    args = parser.parse_args()
    built = build_text()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current == built:
            print("index.html is up to date")
            return 0
        print("index.html is out of date; run: python3 build.py")
        for line in list(difflib.unified_diff(current.splitlines(), built.splitlines(), fromfile="index.html", tofile="rebuilt index.html", lineterm="", n=2))[:80]:
            print(line)
        return 1
    TARGET.write_text(built, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(built):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
