#!/usr/bin/env python3
"""Build the modular and fully self-contained Layout Studio entry pages."""

from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "src" / "index.template.html"
MODULAR_TARGET = ROOT / "index.html"
STANDALONE_TARGET = ROOT / "build" / "index.html"
DOCTYPE = "<!doctype html>\n"
MODULAR_BANNER = (
    "<!-- Generated by webapp/build.py. "
    "Edit webapp/src/index.template.html instead. -->\n"
)
STANDALONE_BANNER = (
    "<!-- Fully self-contained build generated by webapp/build.py. "
    "Do not edit this file directly. -->\n"
)

STYLESHEET_RE = re.compile(
    r'(?P<indent>^[ \t]*)<link\s+rel="stylesheet"\s+href="(?P<path>src/[^"]+\.css)"\s*/?>',
    re.MULTILINE,
)
SCRIPT_RE = re.compile(
    r'(?P<indent>^[ \t]*)<script\s+src="(?P<path>src/[^"]+\.js)"></script>',
    re.MULTILINE,
)


def read_template() -> str:
    template = SOURCE.read_text(encoding="utf-8")
    if not template.startswith(DOCTYPE):
        raise RuntimeError("src/index.template.html must start with <!doctype html>")
    return template.rstrip() + "\n"


def add_banner(document: str, banner: str) -> str:
    return document.replace(DOCTYPE, f"{DOCTYPE}{banner}", 1)


def read_local_asset(relative_path: str) -> str:
    asset = (ROOT / relative_path).resolve()
    source_root = (ROOT / "src").resolve()
    try:
        asset.relative_to(source_root)
    except ValueError as error:
        raise RuntimeError(f"asset must be below webapp/src: {relative_path}") from error
    if not asset.is_file():
        raise RuntimeError(f"referenced asset does not exist: {relative_path}")
    return asset.read_text(encoding="utf-8").rstrip()


def escape_html_terminator(source: str, element: str) -> str:
    """Keep embedded source from prematurely ending an HTML raw-text element."""

    return re.sub(fr"</{element}", fr"<\\/{element}", source, flags=re.IGNORECASE)


def build_modular(template: str) -> str:
    return add_banner(template, MODULAR_BANNER)


def build_standalone(template: str) -> str:
    stylesheet_count = 0
    script_count = 0

    def inline_stylesheet(match: re.Match[str]) -> str:
        nonlocal stylesheet_count
        stylesheet_count += 1
        indent = match.group("indent")
        css = escape_html_terminator(read_local_asset(match.group("path")), "style")
        return f"{indent}<style>\n{css}\n{indent}</style>"

    def inline_script(match: re.Match[str]) -> str:
        nonlocal script_count
        script_count += 1
        indent = match.group("indent")
        javascript = escape_html_terminator(read_local_asset(match.group("path")), "script")
        return f"{indent}<script>\n{javascript}\n{indent}</script>"

    standalone = STYLESHEET_RE.sub(inline_stylesheet, template)
    standalone = SCRIPT_RE.sub(inline_script, standalone)
    if stylesheet_count == 0:
        raise RuntimeError("template does not reference a local stylesheet")
    if script_count == 0:
        raise RuntimeError("template does not reference local scripts")
    if STYLESHEET_RE.search(standalone) or SCRIPT_RE.search(standalone):
        raise RuntimeError("standalone build still contains local asset references")
    if re.search(r'<script\b[^>]*\bsrc\s*=', standalone, flags=re.IGNORECASE):
        raise RuntimeError("standalone build contains an external script source")
    if re.search(r'<link\b[^>]*\brel="stylesheet"', standalone, flags=re.IGNORECASE):
        raise RuntimeError("standalone build contains an external stylesheet")
    return add_banner(standalone, STANDALONE_BANNER)


def show_diff(path: Path, current: str, expected: str) -> None:
    relative = path.relative_to(ROOT).as_posix()
    print(f"{relative} is out of date; run: python3 build.py")
    lines = difflib.unified_diff(
        current.splitlines(),
        expected.splitlines(),
        fromfile=relative,
        tofile=f"rebuilt {relative}",
        lineterm="",
        n=2,
    )
    for line in list(lines)[:80]:
        print(line)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when either generated index.html is stale",
    )
    args = parser.parse_args()

    template = read_template()
    outputs = {
        MODULAR_TARGET: build_modular(template),
        STANDALONE_TARGET: build_standalone(template),
    }

    if args.check:
        stale = False
        for path, expected in outputs.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != expected:
                stale = True
                show_diff(path, current, expected)
            else:
                print(f"{path.relative_to(ROOT).as_posix()} is up to date")
        return 1 if stale else 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT).as_posix()} ({len(content):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
